micronaut:
  application:
    name: demo
datasources:
  default:
    url: jdbc:h2:file:./devDb;MVCC=TRUE;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE;AUTO_SERVER=TRUE
    driverClassName: org.h2.Driver
    username: sa
    password: ''
    schema-generate: create_drop
    dialect: H2
jpa.default.properties.hibernate.hbm2ddl.auto: create
